less privs
dfoxg/kratos-admin-ui pull request #128
Opened 2023-11-29 15:59 UTC by till

- Update: run kratos-admin-ui without root
- Chore: build test image on PR
- Chore: clean-up workflows

2023-12-01 09:40 UTC, dfoxg commented
@till thanks for the pr! Could you remove the dependabot-config? I'm already using mend renovate for updating the packages. Thanks!

2023-12-01 09:44 UTC, dfoxg commented on .github/workflows/build-on-pr.yml
> -      - '!main'
Why did you remove the main exclusion?

2023-12-01 09:44 UTC, dfoxg commented on .github/workflows/build-on-pr.yml
> +    - id: meta
What's the benefit of using this actions instead of running the command directly?

2023-12-01 11:32 UTC, till commented
> @till thanks for the pr! Could you remove the dependabot-config? I'm already using mend renovate for updating the packages. Thanks!

I didn't know if renovate updated the github actions that are used in workflows. It didn't look like it. But I can remove that if you don't like it.

2023-12-01 15:01 UTC, till commented on .github/workflows/build-on-pr.yml
> +      packages: write
This enables GHA's to write to your registry. So you don't need to maintain the token you have in the secret.

2023-12-05 15:58 UTC, dfoxg approved these changes
Thanks for the contribution :)

2023-12-05 16:01 UTC, dfoxg commented
The docker-push fails at the moment - could you have a look at it?

2023-12-05 16:02 UTC, dfoxg requested changes
Build fails

2024-01-18 16:23 UTC, dfoxg commented
closed with version 2.2.0 https://github.com/dfoxg/kratos-admin-ui/releases/tag/v2.2.0

2024-01-18 16:23 UTC, closed without merging